### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by tlyon3** [QuantEcon/Bookshelf#17]
High Priority:
- [x] Admin options/users
- [x] Notification system
- [x] Set up a Docker container for project
- [x] Co-Authors
- [x] Comment/Reply deletion?
- [ ] Search by author name as well

Low*er* priority:
- [ ] Voting on comments and replies
- [ ] Style loading screens
- [ ] Implement view count
- [ ] Implement "Trending" algorithm
- [ ] Registration page
- [ ] Warn users when leaving Edit Profile page if their are changes
- [ ] Implement more robust error handling
- [ ] Refactor and document code
- [x] Migrate OAuth credentials to QuantEcon dev profiles

Suggestions:
- [ ] Organization users
